# Generated by Django 5.0.3 on 2025-03-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loginapplication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("tenant", "Tenant"),
                    ("landlord", "Landlord"),
                ],
                default="tenant",
                max_length=20,
            ),
        ),
    ]
