# Generated by Django 5.0.3 on 2025-03-04 09:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0002_remove_book_student_delete_student"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("unique_id", models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
    ]
