# Generated by Django 5.0.3 on 2025-03-04 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0003_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app1.student",
            ),
        ),
    ]
