# Generated by Django 5.0.3 on 2025-03-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0005_owner_property_remove_book_student_remove_book_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="property_subtype",
            field=models.CharField(
                choices=[
                    ("2BHK", "2BHK"),
                    ("3BHK", "3BHK"),
                    ("4BHK", "4BHK"),
                    ("VILLA", "VILLA"),
                    ("PANT HOUSE", "PANT HOUSE"),
                    ("OTHERS", "OTHERS"),
                ],
                default="OTHERS",
                max_length=20,
            ),
        ),
    ]
