# Generated by Django 5.0.3 on 2025-03-10 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0006_property_property_subtype"),
    ]

    operations = [
        migrations.CreateModel(
            name="RentalProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("location", models.CharField(max_length=255)),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("Apartment", "Apartment"),
                            ("House", "House"),
                            ("Office", "Office"),
                            ("COMMERCIAL", "Commercial"),
                            ("VILLA", "Villa"),
                        ],
                        max_length=50,
                    ),
                ),
                ("rent_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("available_from", models.DateField()),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rental_properties",
                        to="app1.owner",
                    ),
                ),
            ],
        ),
    ]
