# Generated by Django 5.0.3 on 2025-03-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0007_rentalproperty"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentalproperty",
            name="property_subtype",
            field=models.CharField(
                choices=[
                    ("2BHK", "2BHK"),
                    ("3BHK", "3BHK"),
                    ("4BHK", "4BHK"),
                    ("VILLA", "VILLA"),
                    ("PANT HOUSE", "PANT HOUSE"),
                    ("OTHERS", "OTHERS"),
                ],
                default="OTHERS",
                max_length=20,
            ),
        ),
    ]
